---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: cdp-arch-ansible
    image: carlodepieri/docker-archlinux-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true
    ulimits:
      - nofile:65535:65535
    groups: 
      - archs
provisioner:
  name: ansible
  inventory:
    host_vars:
      # setting for the platform instance named 'cdp-arch-ansible'
      cdp-arch-ansible:
        ansible_user: ansible
verifier:
  name: ansible
