---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
  - name: cdp-arch-ansible
    image: carlodepieri/docker-archlinux-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    pre_build_image: true
    ulimits:
      - nofile:65535:65535
    groups: 
      - archs
provisioner:
  name: ansible
  inventory:
    group_vars:
      archs:
        components_to_install:
          - nodejs
          - jdk8-maven
          - jdk11
          - aws
          - micromamba
          - docker
          - docker-compose
          - rust
          - server-extras
          - julia
    host_vars:
      # setting for the platform instance named 'cdp-arch-ansible'
      cdp-arch-ansible:
        ansible_user: ansible
verifier:
  name: ansible

scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    #- idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
