---
name: CI
'on':
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Run Molecule tests.
        uses: robertdebock/molecule-action@5.0.2
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
